spring:
  config:
    import: optional:dotenv:./onAir.env

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${SERVER_MYSQL_URL}
    url: ${LOCAL_MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mysql:
    charset: utf8mb4
    collation: utf8mb4_unicode_ci

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}

springdoc:
  swagger-ui:
    path: /api-test  # swagger-ui ?? ??? ?? ??, ?? ??? ???? http://localhost:8080/swagger-ui/index.html? ????? ?.
    groups-order: DESC # path, query, body, response ??? ??
    tags-sorter: alpha # ??? ??? ??? ??
    operations-sorter: method  # delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}