services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command:
      - --loose-local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: onAir
      MYSQL_USER: onAir
      MYSQL_PASSWORD: onAir123!@#
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - resources_backend

  spring:
    image: yong6/onair:latest
    container_name: spring-app
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms512m"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - db.env
    networks:
      - resources_backend

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - resources_backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - resources_backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
       - "3000:3000"
    networks:
       - resources_backend
    volumes:
       - grafana-storage:/var/lib/grafana
volumes:
  mysql-data:
  grafana-storage:

networks:
  resources_backend:
    external: true

